### PR TITLE
Update forge installer

### PR DESCRIPTION
**Pull request by TaigoStudio**
Hi! I wrote a new Forge installer where many bugs were fixed. 
✅ Support for launching new type versions (1.12 - 1.16.x) 
✅ Support for launching a version with a changed name (1.10 - 1.11.2)
✅ Support for running old-type versions (1.8 - 1.9.4)
✅ Support for running legacy-type version (1.7.10, others have not been tested)
✅ Automatic system for changing links from the minecraftforge.net
✅ Fixed the bug of installation errors of some versions due to parallel downloading and configuration. (The forge configuration files were used before they were downloaded.)
✅Quick launch of the version if it is already installed. You can disable it
✅Automatic installation of the vanilla version if it does not exist.
✅Speed from 3 to 15 seconds
❌Does not have an action logging system
⚠️You need to install HtmlAgilityPack!!!

### CODE REVIEW

**Comment by TaigoStudio** [comment]
Sorry 1.17.x and above are not supported yet. I'll add them later

**Comment by newkincode** [comment]
Did you sponsor Forge? Just kidding, forge doesn't seem to like auto-installers like this.

**Comment by TaigoStudio** [comment]
Together with the fix 1.17-1.20, I want to embed a redirect to their website with ads. That is, before launching, you need to watch forge ads to support their project

**Comment by AlphaBs** [comment]
thank you for contributing! before to merge there are some debates about automation..

**Comment by TaigoStudio** [comment]
Okay but I've read the Forge license agreement and it doesn't explicitly prohibit the use of parsers. I think it's worth leaving ads to support Forge developers.

**Comment by AlphaBs** [comment]
We agreed that leaving advertisement is good idea.

After the successful installation of Forge, advertisements should always be displayed using a method like Process.Start("ad url").

If library users prefer not to display advertisements, they can manually remove the advertising-related code, build the library themselves, and use it accordingly. 

The official CmlLib.Core repository / package never provides forge installer without advertisement.

The responsibility for not displaying advertisements lies entirely with the library modifier.

how do you think about?

**Comment by AlphaBs** [comment]
by the way huge thanks for great works!

**Comment by TaigoStudio** [comment]
There are no objections. Thanks!

**Comment by TaigoStudio** [comment]
Hello everyone Does anyone know where Forge installs these files from? For some reason from there to version.json and install_profile.json. Forge 1.17+ does not start without these files.

**Comment by TaigoStudio** [comment]
Path: net\minecraftforge\forge\1.20-46.0.14\forge-1.20-46.0.14-client.jar

**Comment by TaigoStudio** [comment]
If I add these files (with a slight change to my code), then Minecraft Forge 1.17 and higher is launched
image

**Comment by TaigoStudio** [comment]
I don't want to add these files manually, because it won't be full automation.

**Comment by TaigoStudio** [comment]
image
Maybe someone knows what the problem is?

**Pull request closed without merging**
