### PR TITLE
Update MForge.cs

### PR DESCRIPTION
**Pull request by TaigoStudio**
Hi! I wrote a new Forge installer where many bugs were fixed. 
✅The Forge developer support system has been added. After each use, the Forge advertising page opens

✅ Support for launching newest type versions (1.17 - 1.20.x)
⚠️ To install the latest versions, you must use Java 17.x.x, that is, when initializing the MForge object, you must specify the path to javaw.exe it is this version.
✅ Support for launching new type versions (1.12 - 1.16.x)
✅ Support for launching a version with a changed name (1.10 - 1.11.2)
✅ Support for running old-type versions (1.8 - 1.9.4)
✅ Support for running legacy-type version (1.7.10, others have not been tested)
✅ Automatic system for changing links from the minecraftforge.net
✅ Fixed the bug of installation errors of some versions due to parallel downloading and configuration. (The forge configuration files were used before they were downloaded.)
✅Quick launch of the version if it is already installed. You can disable it
✅Automatic installation of the vanilla version if it does not exist.
✅Fixed a bug installing the client side.

❌Does not have an action logging system
⚠️You need to install HtmlAgilityPack!!!

If you find bugs, then contact me @Tartilla_ (Discord)

### CODE REVIEW

**Comment by TaigoStudio** [comment]
I have tested the following versions:
✅1.20.1
✅1.20
✅1.19.4
✅1.18.2
✅1.17.1
✅1.16.5
✅1.12.2
✅1.11.2
✅1.9.4
✅1.7.10

**Comment by TaigoStudio** [comment]
image

**Comment by AlphaBs** [comment]
You can add new commit on existing PR instead to create new PR!

previous PR and discussions about advertisement: #83

**Comment by TaigoStudio** [comment]
I don't usually use Github, so I don't know such subtleties :(

**Comment by AlphaBs** [comment]
What about to maintain forge installation feature on seperated package? 

- New dependency `HtmlAgilityPack` is only required for Forge installation. Launcher developer who does not want to use this feature are forced to install unnecessary package.

- Forge installation feature is not much related to other features. Seperating packages would help flexible update. 

I can create new repository  `CmlLib.Core.Installers.Forge`, and I can give you a permission to commit directly to the repository. (collaborator)

**Comment by TaigoStudio** [comment]
Yes, let's do that.

**Comment by AlphaBs** [comment]
move to CmlLib/CmlLib.Core.Installer.Forge

**Pull request closed without merging**
